### ISSUE TITLE
not support with codec id 12 and format mp4 :((

### ISSUE THREAD

**Issue by Houangnt** [swhan0329/vehicle_speed_estimation#1]
![image](https://user-images.githubusercontent.com/48252530/112292858-16dd1b80-8cc4-11eb-88e3-9f03bb42e192.png)

**Comment by swhan0329** [comment]
Hello, @NTHoang99

I used .avi file, if you want to use .mp4 please change code like this

```python
fourcc = cv2.VideoWriter_fourcc(*'MPEG')
```

You can find change part using below link.

https://github.com/swhan0329/vehicle_speed_estimation/blob/352c79d41849e30a6c6a47feaae572c25bb66232/main.py#L71
