### ISSUE TITLE
How do you calculate pixel to mm in this projects?

### ISSUE THREAD

**Issue by zaiplanet** [swhan0329/vehicle_speed_estimation#2]
```
      px2m1 = 0.0895
      px2m2 = 0.088
      px2m3 = 0.0774
      px2m4 = 0.0767
      px2m5 = 0.0736
```

please let me know calculate this
Thanks you ~

**Comment by swhan0329** [comment]
@zaiplanet Hello,
That is from Korean formats of lines on the road.
The white line should be 8 meters and the space between white lines should be 12 meters at the highway, Korea.

**Comment by zaiplanet** [comment]
if i set custom polygon area detect, can i calculate to pixel from this area? ^^

**Comment by swhan0329** [comment]
@zaiplanet Yes, if you set new areas,  you should be updated that parameters.

**Comment by zaiplanet** [comment]
@swhan0329 
i try set 2 custom polygon below:
`pg1 = np.array([[490, 400], [380, 400],[260, 470], [410, 475]])`
 `pg2 = np.array([[412, 475], [490, 400], [595, 400], [570, 480]])`

How will i update that parameters ? Do you tell me calculate formula?
Thanks you.

**Comment by swhan0329** [comment]
@zaiplanet 
You should know the real-world length between two points. Then you can get each point's pixel coordinates.
The formula is very simple you can understand it via the below picture.

![image](https://user-images.githubusercontent.com/46466469/141723471-d6dc5e47-c10e-4951-b18c-5829304290a8.png)

**Comment by zaiplanet** [comment]
@swhan0329 
I understand^^ . Thank you so much for your support
